spring.data.mongodb.auto-index-creation=true
server.servlet.context-path=/api
jwt.secretKey=focusarc-super-secret-key-change-in-prod-256bit!!
jwt.expiration-time=9000000
jwt.refresh-expiration-time=604800000
google.client-id=468172227016-rb385r55f5hlm995o0mnfg2ldj7s85jl.apps.googleusercontent.com