spring.data.mongodb.auto-index-creation=true
server.servlet.context-path=/api
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
jwt.secretKey=${JWT_SECRET}
jwt.expiration-time=9000000
jwt.refresh-expiration-time=604800000
google.client-id=${GOOGLE_CLIENT_ID}