import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'doc', id: 'README' },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Domain',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'domain' }],
    },
    {
      type: 'category',
      label: 'ADR',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'adr' }],
    },
    { type: 'doc', id: 'TODO' },
    { type: 'doc', id: 'backlog' },
  ],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
};

export default sidebars;